name: CI

on:
  push:
    branches: [main]
    paths-ignore: ["**/*.md", "LICENSE", ".gitignore"]
  pull_request:
    branches: [main]
    paths-ignore: ["**/*.md", "LICENSE", ".gitignore"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: cplieger/ci/.github/workflows/go-ci.yaml@2eaa3359c4d601496b2168cf4f8a474cd5a1c74b # v1
