name: Security

on:
  pull_request:
    paths: ["go.mod", "go.sum", "Dockerfile", ".github/workflows/security.yml"]
  schedule:
    - cron: "17 5 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    uses: cplieger/ci/.github/workflows/security-scan.yaml@f024f691d9c2fcbaff3c74231a4cb25126630056 # v1
