name: Security

on:
  pull_request:
    paths: ["go.mod", "go.sum", "Dockerfile", ".github/workflows/security.yml"]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    uses: cplieger/ci/.github/workflows/security-scan.yaml@e69f2cbaa1ee46d48cbabf7d0858ae46720152ef # v1
