name: Security

on:
  pull_request:
    paths: ["go.mod", "go.sum", "Dockerfile", ".github/workflows/security.yml"]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    uses: cplieger/ci/.github/workflows/security-scan.yaml@c3d6df9d783f0d70aea92c8c1fdba1cfb821a483 # v1
